### PR TITLE
+ Changed "timeout" between requests to 15 mins, added "timeoutOnErro…

### PR DESCRIPTION
**Pull request by mwittig**
…r" (1 min) which applies if last request failed
- Added API key handling following issue https://github.com/josecastroleon/pimatic-openweather/issues/9
- Updated README

### CODE REVIEW

**Comment by pimagical** [comment]
error [pimatic-openweather]: Unable to parse response: Invalid API key. Please see http://openweathermap.org/faq#error401 for more info.

**Comment by mwittig** [comment]
@pimagical See [README](https://github.com/josecastroleon/pimatic-openweather/blob/master/README.md)

**Comment by pimagical** [comment]
Ok thanks!

**Comment by mwittig** [comment]
@sweetpi Sorry, I did not notice your earlier comment on placement of apiKey. You're right, it would be more sensible to have the apiKey as part of plugin configuration. Do you want me do this? It would be a breaking change, but if communicated properly users can hopfully deal with it.

**Comment by sweetpi** [comment]
@mwittig no worries, I did move it to the plugin config and added some code to do it automatically, if defined for a device.

**Pull request merged**
